### ISSUE TITLE
Changing Alpha doesn't seem to work?

### ISSUE THREAD

**Issue by Croccy22** [Flafla2/Vive-Teleporter#18]
Not sure if I'm just doing something wrong (Likely!)

But I have tried to change the Border Alpha slider but it had no effect in game. Also the ground Alpha slider can't be modified.

I wanted to make the grid translucent so it doesn't show up as much in dark environments.

**Comment by Flafla2** [comment]
Part of this is a bug (the Border Alpha slider actually doesn't work due to a UI bug, I'm working on a fix now).  However if you want the Border Alpha to change in game, you're going to need to edit the ViveNavMesh animator (``Assets/Vive-Teleporter/Art/Navmesh Animations/Enabled.anim`).

Edit: Note, the aforementioned UI bug is now fixed.

**Comment by local306** [comment]
Sorry to revive this, but I'm having the same problem. I've duplicated the animation, set the duplicate as the clip for Enabled state, and cleared both the alpha properties associated with it. However, the values are still somehow being set to 1 and I cannot manipulate the sliders. Is there somewhere else where this value is being set?
