### ISSUE TITLE
IVRSystem errors

### ISSUE THREAD

**Issue by dotcommer** [Flafla2/Vive-Teleporter#24]
Trying to import the assets into my scene and I get a flood of errors in console about "The namespace 'Valve.VR' already contains a definition for 'IVRSystem'"

Error starts in "openvr_api" line 16 "public struct IVRSystem".

Has anyone else come across this issue?

Using Unity 5.40f3

**Comment by dr0idattack** [comment]
I received the same error. Did you ever resolve the problem?

**Comment by dr0idattack** [comment]
I figured it out. Don't drag the whole Vive-Teleporter directory into your Unity project. Just put the Vive-Teleporter\Assets\Vive-Teleporter directory into your Unity project's Assets directory .

**Comment by Flafla2** [comment]
Hi, sorry for the late response.  I would recommend downloading the [unitypackage from the Releases page](https://github.com/Flafla2/Vive-Teleporter/releases) instead of downloading the repo directly.  However, if you would prefer to download the repo for bleeding-edge changes, you should only import the Vive-Teleporter directory.
