### ISSUE TITLE
Navmesh visual generation broken under some circumstances

### ISSUE THREAD

**Issue by justonia** [Flafla2/Vive-Teleporter#39]
See attached screenshots. I will try and get a sample project uploaded at some point, but this is easy to replicate with more complicated level geometry than is in the sample scenes.

![meshbad](https://cloud.githubusercontent.com/assets/89791/21549479/a61b39ae-cdaf-11e6-8ffc-22b823ff09e2.PNG)
![navsource](https://cloud.githubusercontent.com/assets/89791/21549482/a7967ef6-cdaf-11e6-9faa-e47829c22906.PNG)

**Comment by Flafla2** [comment]
What do things look like in game?  I'm guessing this is only a problem with the border generation step, but it could also be an issue with the Navmesh extraction step.

My first stab at a solution is to increase the duplicate detection threshold [here](https://github.com/Flafla2/Vive-Teleporter/blob/master/Assets/Vive-Teleporter/Scripts/ViveNavMeshEditor.cs#L329) - maybe to ``0.10f``?

Also, possibly you have more than 65535 vertices in your navmesh, which would break things.  Let me know if this is true (you should've gotten an error in console too).

**Comment by justonia** [comment]
Nope definitely don't have more than 65k verts, and the tolerance fix doesn't change anything.

**Comment by justonia** [comment]
I managed to repro in a modified version of the Vive testbed scene.

[Example Scenes (broken).zip](https://github.com/Flafla2/Vive-Teleporter/files/683166/Example.Scenes.broken.zip)

**Comment by Flafla2** [comment]
I have identified the cause of this issue.  Apparently Unity's Navmesh baking system is more unpredictable than I originally thought, due to that pesky voxel size (this was the cause of #15 as well).  In the example you provided (thank you, by the way!) there was a height differential between each side of the upper plane:

![capture](https://cloud.githubusercontent.com/assets/1498072/21630634/179e6394-d201-11e6-9d88-0162ee72d93f.PNG)

Notice how the left side of the navmesh is higher than the right side.  My system interpreted one of these triangles as a sloped surface, and omitted it in the navmesh calculation.  From what I understand about Unity's Navmesh system, this is accepatble/intended behavior as the height differential is within the current Navmesh voxel size (0.16666667).  There are a few ways to fix this problem:

1. [Cheap] Take voxel size into account when determining if a face is sloped.  This at least prevents faces from disappearing but causes a warped navmesh visualization.
2. [Cheap] Clamp the navmesh to the top / bottom of each navmesh voxel.  This will prevent any visual warping but may lead to the visualization to appear "floating" above the ground (by at most the voxel size).
3. [Expensive] For each vertex in the Navmesh, raycast downwards and set the vertex position to exactly that coordinate.  This will achieve the best visual results, but takes a loooong time.

In the near future I will implement all three methods shown above.  For a quick and dirty fix for your own build, change [this](https://github.com/Flafla2/Vive-Teleporter/blob/master/Assets/Vive-Teleporter/Scripts/ViveNavMeshEditor.cs#L207) value to ``true``, bypassing the slope check.

**Comment by justonia** [comment]
Thanks for looking into this!
